language: nodejs
env:
  - TEMPLATE="templates/qcow/centos-6.json"
  - TEMPLATE="templates/qcow/centos-7.json"
  - TEMPLATE="templates/qcow/debian-8.json"
  - TEMPLATE="templates/qcow/debian-9.json"
  - TEMPLATE="templates/qcow/fedora-27.json"
  - TEMPLATE="templates/qcow/fedora-28.json"
  - TEMPLATE="templates/qcow/fedora-29.json"
  - TEMPLATE="templates/qcow/ubuntu-1604-desktop.json"
  - TEMPLATE="templates/qcow/ubuntu-1604.json"
  - TEMPLATE="templates/qcow/ubuntu-1704.json"
  - TEMPLATE="templates/qcow/ubuntu-1710.json"
  - TEMPLATE="templates/qcow/ubuntu-1804-desktop.json"
  - TEMPLATE="templates/qcow/ubuntu-1804.json"
  - TEMPLATE="templates/qcow/ubuntu-1810-desktop.json"
  - TEMPLATE="templates/qcow/ubuntu-1810.json"
  - TEMPLATE="templates/qcow/ubuntu-1904.json"
script:
  - source ./buildTravis.sh
before_install:
  - >-
    openssl aes-256-cbc -k "$ENCRYPT_KEY" -in ./resources/secrets/id_rsa.enc
    -out ./resources/secrets/id_rsa -d;
  - 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -'
  - >-
    sudo add-apt-repository "deb [arch=amd64]
    https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
addons:
  apt:
    packages:
      - docker
