language: nodejs
services:
  - docker
jobs:
  include:
    - stage: config/packer/alpine-3.10-docker.yaml
      env: CONFIG="config/packer/alpine-3.10-docker.yaml" MODE="packer" SCOPE=H1
    - stage: config/packer/alpine-3.10-docker.yaml
      env: CONFIG="config/packer/alpine-3.10-docker.yaml" MODE="packer" SCOPE=RBX
    - stage: config/packer/alpine-3.10.yaml
      env: CONFIG="config/packer/alpine-3.10.yaml" MODE="packer" SCOPE=H1
    - stage: config/packer/alpine-3.10.yaml
      env: CONFIG="config/packer/alpine-3.10.yaml" MODE="packer" SCOPE=RBX
    - stage: config/packer/centos-7.yaml
      env: CONFIG="config/packer/centos-7.yaml" MODE="packer" SCOPE=H1
    - stage: config/packer/centos-7.yaml
      env: CONFIG="config/packer/centos-7.yaml" MODE="packer" SCOPE=RBX
    - stage: config/packer/debian-10.yaml
      env: CONFIG="config/packer/debian-10.yaml" MODE="packer" SCOPE=H1
    - stage: config/packer/debian-10.yaml
      env: CONFIG="config/packer/debian-10.yaml" MODE="packer" SCOPE=RBX
    - stage: config/packer/debian-8.yaml
      env: CONFIG="config/packer/debian-8.yaml" MODE="packer" SCOPE=H1
    - stage: config/packer/debian-8.yaml
      env: CONFIG="config/packer/debian-8.yaml" MODE="packer" SCOPE=RBX
    - stage: config/packer/debian-9.yaml
      env: CONFIG="config/packer/debian-9.yaml" MODE="packer" SCOPE=H1
    - stage: config/packer/debian-9.yaml
      env: CONFIG="config/packer/debian-9.yaml" MODE="packer" SCOPE=RBX
    - stage: config/packer/debian-docker.yaml
      env: CONFIG="config/packer/debian-docker.yaml" MODE="packer" SCOPE=H1
    - stage: config/packer/debian-docker.yaml
      env: CONFIG="config/packer/debian-docker.yaml" MODE="packer" SCOPE=RBX
    - stage: config/packer/fedora-28.yaml
      env: CONFIG="config/packer/fedora-28.yaml" MODE="packer" SCOPE=H1
    - stage: config/packer/fedora-28.yaml
      env: CONFIG="config/packer/fedora-28.yaml" MODE="packer" SCOPE=RBX
    - stage: config/packer/fedora-29.yaml
      env: CONFIG="config/packer/fedora-29.yaml" MODE="packer" SCOPE=H1
    - stage: config/packer/fedora-29.yaml
      env: CONFIG="config/packer/fedora-29.yaml" MODE="packer" SCOPE=RBX
    - stage: config/packer/fedora-30.yaml
      env: CONFIG="config/packer/fedora-30.yaml" MODE="packer" SCOPE=H1
    - stage: config/packer/fedora-30.yaml
      env: CONFIG="config/packer/fedora-30.yaml" MODE="packer" SCOPE=RBX
    - stage: config/packer/fedora-31.yaml
      env: CONFIG="config/packer/fedora-31.yaml" MODE="packer" SCOPE=H1
    - stage: config/packer/fedora-31.yaml
      env: CONFIG="config/packer/fedora-31.yaml" MODE="packer" SCOPE=RBX
    - stage: config/packer/ubuntu-1604-desktop.yaml
      env: CONFIG="config/packer/ubuntu-1604-desktop.yaml" MODE="packer" SCOPE=H1
    - stage: config/packer/ubuntu-1604-desktop.yaml
      env: CONFIG="config/packer/ubuntu-1604-desktop.yaml" MODE="packer" SCOPE=RBX
    - stage: config/packer/ubuntu-1604.yaml
      env: CONFIG="config/packer/ubuntu-1604.yaml" MODE="packer" SCOPE=H1
    - stage: config/packer/ubuntu-1604.yaml
      env: CONFIG="config/packer/ubuntu-1604.yaml" MODE="packer" SCOPE=RBX
    - stage: config/packer/ubuntu-1804-desktop.yaml
      env: CONFIG="config/packer/ubuntu-1804-desktop.yaml" MODE="packer" SCOPE=H1
    - stage: config/packer/ubuntu-1804-desktop.yaml
      env: CONFIG="config/packer/ubuntu-1804-desktop.yaml" MODE="packer" SCOPE=RBX
    - stage: config/packer/ubuntu-1804.yaml
      env: CONFIG="config/packer/ubuntu-1804.yaml" MODE="packer" SCOPE=H1
    - stage: config/packer/ubuntu-1804.yaml
      env: CONFIG="config/packer/ubuntu-1804.yaml" MODE="packer" SCOPE=RBX
    - stage: config/packer/ubuntu-1810-desktop.yaml
      env: CONFIG="config/packer/ubuntu-1810-desktop.yaml" MODE="packer" SCOPE=H1
    - stage: config/packer/ubuntu-1810-desktop.yaml
      env: CONFIG="config/packer/ubuntu-1810-desktop.yaml" MODE="packer" SCOPE=RBX
    - stage: config/packer/ubuntu-1810.yaml
      env: CONFIG="config/packer/ubuntu-1810.yaml" MODE="packer" SCOPE=H1
    - stage: config/packer/ubuntu-1810.yaml
      env: CONFIG="config/packer/ubuntu-1810.yaml" MODE="packer" SCOPE=RBX
    - stage: config/packer/ubuntu-1904-desktop.yaml
      env: CONFIG="config/packer/ubuntu-1904-desktop.yaml" MODE="packer" SCOPE=H1
    - stage: config/packer/ubuntu-1904-desktop.yaml
      env: CONFIG="config/packer/ubuntu-1904-desktop.yaml" MODE="packer" SCOPE=RBX
    - stage: config/packer/ubuntu-1904.yaml
      env: CONFIG="config/packer/ubuntu-1904.yaml" MODE="packer" SCOPE=H1
    - stage: config/packer/ubuntu-1904.yaml
      env: CONFIG="config/packer/ubuntu-1904.yaml" MODE="packer" SCOPE=RBX
script:
  - travis_retry ./buildTravis.sh
before_install:
  - ./installTravis.sh "$ENCRYPT_KEY"
