services:
  - docker
language: minimal
dist: xenial
jobs:
  include:
    - stage: primary
      env: CONFIG="config/packer/alpine-3.11-docker.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/alpine-3.11-docker.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/alpine-3.11.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/alpine-3.11.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/centos-7.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/centos-7.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/debian-10.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/debian-10.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/debian-8.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/debian-8.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/debian-9.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/debian-9.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/debian-docker.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/debian-docker.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/fedora-29.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/fedora-29.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/fedora-30.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/fedora-30.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/fedora-31.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/fedora-31.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1604-desktop.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1604-desktop.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1604.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1604.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1804-desktop.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1804-desktop.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1804.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1804.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1904-desktop.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1904-desktop.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1904.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1904.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1910-desktop.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1910-desktop.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1910.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1910.yaml" MODE="packer" SCOPE=RBX
script:
  - ./buildTravis.sh
before_install:
  - ./installTravis.sh "$ENCRYPT_KEY"
