language: nodejs
env:
  - TEMPLATE="templates/qcow/centos-6.json" SCOPE=H1
  - TEMPLATE="templates/qcow/centos-7.json" SCOPE=H1
  - TEMPLATE="templates/qcow/debian-8.json" SCOPE=H1
  - TEMPLATE="templates/qcow/debian-9.json" SCOPE=H1
  - TEMPLATE="templates/qcow/fedora-27.json" SCOPE=H1
  - TEMPLATE="templates/qcow/fedora-28.json" SCOPE=H1
  - TEMPLATE="templates/qcow/fedora-29.json" SCOPE=H1
  - TEMPLATE="templates/qcow/ubuntu-1604-desktop.json" SCOPE=H1
  - TEMPLATE="templates/qcow/ubuntu-1604.json" SCOPE=H1
  - TEMPLATE="templates/qcow/ubuntu-1704.json" SCOPE=H1
  - TEMPLATE="templates/qcow/ubuntu-1710.json" SCOPE=H1
  - TEMPLATE="templates/qcow/ubuntu-1804-desktop.json" SCOPE=H1
  - TEMPLATE="templates/qcow/ubuntu-1804.json" SCOPE=H1
  - TEMPLATE="templates/qcow/ubuntu-1810-desktop.json" SCOPE=H1
  - TEMPLATE="templates/qcow/ubuntu-1810.json" SCOPE=H1
  - TEMPLATE="templates/qcow/ubuntu-1904.json" SCOPE=H1
  - TEMPLATE="templates/qcow/centos-6.json" SCOPE=RBX
  - TEMPLATE="templates/qcow/centos-7.json" SCOPE=RBX
  - TEMPLATE="templates/qcow/debian-8.json" SCOPE=RBX
  - TEMPLATE="templates/qcow/debian-9.json" SCOPE=RBX
  - TEMPLATE="templates/qcow/fedora-27.json" SCOPE=RBX
  - TEMPLATE="templates/qcow/fedora-28.json" SCOPE=RBX
  - TEMPLATE="templates/qcow/fedora-29.json" SCOPE=RBX
  - TEMPLATE="templates/qcow/ubuntu-1604-desktop.json" SCOPE=RBX
  - TEMPLATE="templates/qcow/ubuntu-1604.json" SCOPE=RBX
  - TEMPLATE="templates/qcow/ubuntu-1704.json" SCOPE=RBX
  - TEMPLATE="templates/qcow/ubuntu-1710.json" SCOPE=RBX
  - TEMPLATE="templates/qcow/ubuntu-1804-desktop.json" SCOPE=RBX
  - TEMPLATE="templates/qcow/ubuntu-1804.json" SCOPE=RBX
  - TEMPLATE="templates/qcow/ubuntu-1810-desktop.json" SCOPE=RBX
  - TEMPLATE="templates/qcow/ubuntu-1810.json" SCOPE=RBX
  - TEMPLATE="templates/qcow/ubuntu-1904.json" SCOPE=RBX
script:
  - ./buildTravis.sh
before_install:
  - ./installTravis.sh "$ENCRYPT_KEY"
