language: nodejs
services:
  - docker


before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

jobs:
  include:
    - stage: primary
      env: CONFIG="config/packer/alpine-3.10-docker.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/alpine-3.10-docker.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/alpine-3.10.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/alpine-3.10.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/centos-7.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/centos-7.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/debian-10.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/debian-10.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/debian-8.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/debian-8.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/debian-9.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/debian-9.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/debian-docker.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/debian-docker.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/fedora-28.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/fedora-28.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/fedora-29.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/fedora-29.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/fedora-30.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/fedora-30.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/fedora-31.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/fedora-31.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1604-desktop.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1604-desktop.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1604.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1604.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1804-desktop.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1804-desktop.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1804.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1804.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1810-desktop.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1810-desktop.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1810.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1810.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1904-desktop.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1904-desktop.yaml" MODE="packer" SCOPE=RBX
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1904.yaml" MODE="packer" SCOPE=H1
    - stage: primary
      env: CONFIG="config/packer/ubuntu-1904.yaml" MODE="packer" SCOPE=RBX
script:
  - travis_retry ./buildTravis.sh
before_install:
  - ./installTravis.sh "$ENCRYPT_KEY"
