language: nodejs
env:
  - CONFIG="config/qcow/fedora-27.yaml" MODE="packer" SCOPE=H1
  - CONFIG="config/qcow/fedora-28.yaml" MODE="packer" SCOPE=H1
  - CONFIG="config/qcow/fedora-29.yaml" MODE="packer" SCOPE=H1
  - CONFIG="config/qcow/centos-6.yaml" MODE="packer" SCOPE=H1
  - CONFIG="config/qcow/centos-7.yaml" MODE="packer" SCOPE=H1
  - CONFIG="config/qcow/debian-8.yaml" MODE="packer" SCOPE=H1
  - CONFIG="config/qcow/debian-9.yaml" MODE="packer" SCOPE=H1
  - CONFIG="config/qcow/ubuntu-1604-desktop.yaml" MODE="packer" SCOPE=H1
  - CONFIG="config/qcow/ubuntu-1604.yaml" MODE="packer" SCOPE=H1
  - CONFIG="config/qcow/ubuntu-1704.yaml" MODE="packer" SCOPE=H1
  - CONFIG="config/qcow/ubuntu-1710.yaml" MODE="packer" SCOPE=H1
  - CONFIG="config/qcow/ubuntu-1804-desktop.yaml" MODE="packer" SCOPE=H1
  - CONFIG="config/qcow/ubuntu-1804.yaml" MODE="packer" SCOPE=H1
  - CONFIG="config/qcow/ubuntu-1810-desktop.yaml" MODE="packer" SCOPE=H1
  - CONFIG="config/qcow/ubuntu-1810.yaml" MODE="packer" SCOPE=H1
  - CONFIG="config/qcow/ubuntu-1904.yaml" MODE="packer" SCOPE=H1
  - CONFIG="config/qcow/fedora-27.yaml" MODE="packer" SCOPE=RBX
  - CONFIG="config/qcow/fedora-28.yaml" MODE="packer" SCOPE=RBX
  - CONFIG="config/qcow/fedora-29.yaml" MODE="packer" SCOPE=RBX
  - CONFIG="config/qcow/centos-6.yaml" MODE="packer" SCOPE=RBX
  - CONFIG="config/qcow/centos-7.yaml" MODE="packer" SCOPE=RBX
  - CONFIG="config/qcow/debian-8.yaml" MODE="packer" SCOPE=RBX
  - CONFIG="config/qcow/debian-9.yaml" MODE="packer" SCOPE=RBX
  - CONFIG="config/qcow/ubuntu-1604-desktop.yaml" MODE="packer" SCOPE=RBX
  - CONFIG="config/qcow/ubuntu-1604.yaml" MODE="packer" SCOPE=RBX
  - CONFIG="config/qcow/ubuntu-1704.yaml" MODE="packer" SCOPE=RBX
  - CONFIG="config/qcow/ubuntu-1710.yaml" MODE="packer" SCOPE=RBX
  - CONFIG="config/qcow/ubuntu-1804-desktop.yaml" MODE="packer" SCOPE=RBX
  - CONFIG="config/qcow/ubuntu-1804.yaml" MODE="packer" SCOPE=RBX
  - CONFIG="config/qcow/ubuntu-1810-desktop.yaml" MODE="packer" SCOPE=RBX
  - CONFIG="config/qcow/ubuntu-1810.yaml" MODE="packer" SCOPE=RBX
  - CONFIG="config/qcow/ubuntu-1904.yaml" MODE="packer" SCOPE=RBX
script:
  - travis_retry ./buildTravis.sh
before_install:
  - ./installTravis.sh "$ENCRYPT_KEY"
