#!/bin/bash

echo $(date) >> /userdata

end_time=$(date +"%s")
duration=`expr ${end_time} - %%REQUEST_TIME%%`;

curl -XPOST "http://%%INFLUXDB_HOST%%/write?db=recommended_image" \
    -u "%%INFLUXDB_USER%%:%%INFLUXDB_PASSWORD%%" \
    --data-binary "startup_time,vm_type=%%VM_TYPE%%,image=%%IMAGE_ID%%,image_name=%%IMAGE_NAME% time=${duration} ${end_time}000000000"