name: alpine-edge
distro: alpine
edition: server
codename: ''
pname: Alpine Linux Edge
arch: x64
version: '3'
disk_size: '5'
uefi_support: '0'
template_file: templates/manual/alpine-3.10-syslinux.json
