name: docker-alpine
distro: alpine
edition: server
codename: ''
pname: Alpine Docker
arch: x64
version: '3.10'
disk_size: '5'
uefi_support: '0'
template_file: templates/manual/alpine-3.10-docker.json
