name: alpine-3.14-docker
distro: alpine
edition: server
codename: 'stable'
pname: Alpine 3.14 Docker
arch: x64
version: '3.14'
disk_size: '5'
cloud_init_install: true
template_file: templates/manual/alpine-3.14-docker.json
uefi_support: true
repology_repo: alpine_3_14
