name: alpine-3.21-docker
distro: alpine
edition: docker
codename: 'stable'
pname: Alpine 3.21 Docker
arch: x64
version: '3.21'
build: true
disk_size: '5'
cloud_init_install: true
template_file: templates/manual/alpine-3.21-docker.json
uefi_support: true
repology_repo: alpine_3_21
