name: alpine-3.12-docker
distro: alpine
edition: server
codename: 'stable'
pname: Alpine 3.12 Docker
arch: x64
version: '3.12'
disk_size: '5'
cloud_init_install: true
template_file: templates/manual/alpine-3.12-docker.json
uefi_support: '1'
