name: alpine-3.13-server
distro: alpine
edition: server
codename: 'stable'
pname: Alpine 3.13 Server
arch: x64
version: '3.13'
disk_size: '5'
cloud_init_install: true
template_file: templates/manual/alpine-3.13-syslinux.json
uefi_support: true
