name: docker-alpine
distro: docker
edition: server
codename: docker
pname: Docker (Alpine-based)
arch: x64
version: 'alpine'
disk_size: '5'
uefi_support: '0'
template_file: templates/manual/alpine-docker.json
stage: 'secondary'
