name: centos-8
codename: core
pname: CentOS 8
distro: centos
edition: server
arch: x64
version: '8'
download_url: 'https://koji.mbox.centos.org/pkgs/packages/CentOS-8-GenericCloud/8.0.1905/9/images/CentOS-8-GenericCloud-8.0.1905-9.x86_64.qcow2'
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_ds_dir: /usr/lib/python2.7/site-packages/cloudinit/sources/
custom_scripts:
  - ./scripts/centos/centos-7.sh
#  - ./scripts/centos/cli.sh
uefi_support: '0'
selinux: '1'
format: qcow
