name: centos-8
codename: core
pname: CentOS 8
distro: centos
edition: server
arch: x64
version: '8'
download_url: 'https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-GenericCloud-8-20220125.1.x86_64.qcow2'
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_install: false
custom_scripts:
  - ./scripts/resolv.sh
  - ./scripts/fstab.sh
  - ./scripts/centos/centos-8.sh
  - ./scripts/centos/cli.sh
  - ./scripts/relabel.sh
  - ./scripts/check_df.sh
uefi_support: true
cli_support: true
source_image: 'centos:8'
selinux: '1'
format: qcow
repology_repo: centos_8