name: centos-7
codename: core
pname: CentOS 7
distro: centos
edition: server
arch: x64
version: '7'
download_url: 'http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2'
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_ds_src: ./resources/cloud-init/ds_v2/DataSourceRbxCloud.py
cloud_init_ds_dir: /usr/lib/python2.7/site-packages/cloudinit/sources/
custom_scripts:
  - ./scripts/fstab.sh
  - ./scripts/centos/centos-7.sh
  - ./scripts/centos/cli.sh
# uefi_support: '1'
selinux: '1'
format: qcow
