name: debian-9-docker
codename: docker
pname: Debian GNU/Linux (with Docker)
distro: debian
edition: server
arch: x64
version: '9'
download_url: >-
  https://cdimage.debian.org/cdimage/openstack/current-9/debian-9-openstack-amd64.qcow2
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_ds_dir: /usr/lib/python3/dist-packages/cloudinit/sources/
custom_scripts:
  - ./scripts/debian/debian-8-jessie.sh
  - ./scripts/debian/docker.sh
uefi_support: '0'
format: qcow
