name: debian-10-buster
codename: buster
pname: Debian GNU/Linux 10 (buster)
distro: debian
edition: server
arch: x64
version: '10'
download_url: >-
  http://cdimage.debian.org/cdimage/openstack/testing/debian-testing-openstack-amd64.qcow2
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_ds_dir: /usr/lib/python3/dist-packages/cloudinit/sources/
custom_scripts:
  - ./scripts/debian/debian-10-buster.sh
uefi_support: '0'
format: qcow
image_tenant_access: 5c5d7eb1a5e06e1eb5532770
