name: debian-docker
codename: docker
pname: Debian GNU/Linux (with Docker)
distro: debian
edition: docker
arch: x64
version: '11'
download_url: >-
  http://cdimage.debian.org/images/cloud/bullseye/daily/latest/debian-11-genericcloud-amd64-daily.qcow2
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_install: false
custom_scripts:
  - ./scripts/resolv.sh
  - ./scripts/fstab.sh
  - ./scripts/debian/debian-10-buster.sh
  # - ./scripts/debian/cli.sh
  - ./scripts/debian/docker.sh
  - ./scripts/apt_clean.sh
  - ./scripts/check_df.sh
uefi_support: true
cli_support: true
format: qcow
repology_repo: debian_stable