name: debian-11-bullseye
codename: bullseye
pname: Debian GNU/Linux 11 (bullseye)
distro: debian
edition: server
arch: x64
version: '11'
download_url: >-
  https://cloud.debian.org/images/cloud/bullseye/20220328-962/debian-11-genericcloud-amd64-20220328-962.qcow2
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_install: false
custom_scripts:
  - ./scripts/resolv.sh
  - ./scripts/fstab.sh
  - ./scripts/debian/debian-10-buster.sh
  # - ./scripts/debian/cli.sh
  - ./scripts/apt_clean.sh
  - ./scripts/check_df.sh
uefi_support: true
cli_support: true
format: qcow
repology_repo: debian_stable
