name: debian-10-buster
codename: buster
pname: Debian GNU/Linux 10 (buster)
distro: debian
edition: server
arch: x64
version: '10'
download_url: >-
  http://cdimage.debian.org/images/cloud/OpenStack/current-10/debian-10-openstack-amd64.qcow2
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_ds_dir: /usr/lib/python3/dist-packages/cloudinit/sources/
custom_scripts:
  - ./scripts/fstab.sh
  - ./scripts/debian/debian-10-buster.sh
  - ./scripts/debian/cli.sh
# uefi_support: '1'
format: qcow
