name: debian-8-jessie
codename: jessie
pname: Debian GNU/Linux 8 (jessie)
distro: debian
edition: server
arch: x64
version: '8'
download_url: >-
  https://cdimage.debian.org/cdimage/openstack/archive/8.11.5-20181005/debian-8.11.5-20181005-openstack-amd64.qcow2
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_install: true
cloud_init_ds_src: ./resources/cloud-init/ds/DataSourceRbxCloud.py
custom_scripts:
  - ./scripts/fstab.sh
  - ./scripts/debian/debian-8-jessie.sh
  - ./scripts/debian/cli.sh
uefi_support: '1'
format: qcow
