name: debian-9-stretch
codename: stretch
pname: Debian GNU/Linux 9 (stretch)
distro: debian
edition: server
arch: x64
version: '9'
download_url: >-
  https://cdimage.debian.org/cdimage/openstack/current-9/debian-9-openstack-amd64.qcow2
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_ds_dir: /usr/lib/python3/dist-packages/cloudinit/sources/
custom_scripts:
  - ./scripts/fstab.sh
  - ./scripts/debian/debian-8-jessie.sh
  - ./scripts/debian/cli.sh
# uefi_support: '1'
format: qcow
