name: debian-9-stretch
codename: stretch
pname: Debian GNU/Linux 9 (stretch)
distro: debian
edition: server
arch: x64
version: '9'
download_url: >-
  https://cdimage.debian.org/cdimage/openstack/current-9/debian-9-openstack-amd64.qcow2
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_ds_src: ./resources/cloud-init/ds/DataSourceRbxCloud.py
cloud_init_install: true
custom_scripts:
  - ./scripts/resolv.sh
  - ./scripts/fstab.sh
  - ./scripts/debian/debian-9-stretch.sh
  - ./scripts/debian/cli.sh
  - ./scripts/check_df.sh
uefi_support: true
format: qcow
