name: debian-10-buster
codename: buster
pname: Debian GNU/Linux 10 (buster)
distro: debian
edition: server
arch: x64
version: '10'
download_url: >-
  http://cdimage.debian.org/images/cloud/OpenStack/current-10/debian-10-openstack-amd64.qcow2
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_ds_src: ./resources/cloud-init/ds_v2/DataSourceRbxCloud.py
cloud_init_install: true
custom_scripts:
  - ./scripts/resolv.sh
  - ./scripts/fstab.sh
  - ./scripts/debian/debian-10-buster.sh
  - ./scripts/debian/cli.sh
  - ./scripts/apt_clean.sh
  - ./scripts/check_df.sh
uefi_support: true
cli_support: true
format: qcow
repology_repo: debian_stable
