name: debian-docker
codename: docker
pname: Debian GNU/Linux (with Docker)
distro: debian
edition: docker
arch: x64
version: '10'
download_url: >-
  http://cdimage.debian.org/images/cloud/OpenStack/current-10/debian-10-openstack-amd64.qcow2
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_install: false
custom_scripts:
  - ./scripts/resolv.sh
  - ./scripts/fstab.sh
  - ./scripts/debian/debian-10-buster.sh
  - ./scripts/debian/cli.sh
  - ./scripts/debian/docker.sh
uefi_support: true
format: qcow
