name: fedora-31
codename: core
pname: Fedora 31
distro: fedora
edition: server
arch: x64
version: '31'
download_url: >-
  https://ftp.icm.edu.pl/pub/Linux/fedora/linux/releases/test/31_Beta/Cloud/x86_64/images/Fedora-Cloud-Base-31_Beta-1.1.x86_64.qcow2
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_ds_src: ./resources/cloud-init/ds_v2/DataSourceRbxCloud.py
cloud_init_ds_dir: /usr/lib/python3.7/site-packages/cloudinit/sources
custom_scripts:
  - ./scripts/fedora/fedora-31.sh
  # - ./scripts/fedora/cli_dnf.sh
uefi_support: '0'
selinux: '1'
format: qcow
