name: fedora-32
codename: core
pname: Fedora 32
distro: fedora
edition: server
arch: x64
version: '32'
download_url: >-
  https://ftp.icm.edu.pl/pub/Linux/fedora/linux/releases/32/Cloud/x86_64/images/Fedora-Cloud-Base-32-1.6.x86_64.qcow2
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_ds_src: ./resources/cloud-init/ds_v2/DataSourceRbxCloud.py
cloud_init_install: true
custom_scripts:
  - ./scripts/fstab.sh
  - ./scripts/fedora/fedora-31.sh
  - ./scripts/fedora/cli_dnf.sh
  - ./scripts/relabel.sh
source_image: 'fedora:31'
uefi_support: true
selinux: '1'
format: qcow
