name: fedora-33
codename: core
pname: Fedora 33
distro: fedora
edition: server
arch: x64
version: '33'
download_url: >-
  https://ftp.icm.edu.pl/pub/Linux/fedora/linux/releases/33/Cloud/x86_64/images/Fedora-Cloud-Base-33-1.2.x86_64.qcow2
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_install: false
custom_scripts:
  - ./scripts/resolv.sh
  - ./scripts/fstab.sh
  - ./scripts/fedora/fedora-31.sh
  - ./scripts/fedora/fedora-33-plus.sh
  # - ./scripts/fedora/cli_dnf.sh
  - ./scripts/relabel.sh
  - ./scripts/check_df.sh
source_image: 'fedora:33'
uefi_support: false
cli_support: true
selinux: '1'
format: qcow
repology_repo: 'fedora_33'
