name: fedora-31
codename: core
pname: Fedora 31
distro: fedora
edition: server
arch: x64
version: '31'
download_url: >-
  https://ftp.icm.edu.pl/pub/Linux/fedora/linux/releases/31/Cloud/x86_64/images/Fedora-Cloud-Base-31-1.9.x86_64.qcow2
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_ds_src: ./resources/cloud-init/ds_v2/DataSourceRbxCloud.py
cloud_init_install: true
custom_scripts:
  - ./scripts/fstab.sh
  - ./scripts/fedora/fedora-31.sh
  - ./scripts/fedora/cli_dnf.sh
uefi_support: true
selinux: '1'
format: qcow
