name: fedora-33
codename: core
pname: Fedora 33
distro: fedora
edition: server
arch: x64
version: '33'
download_url: >-
  https://ftp.icm.edu.pl/pub/Linux/fedora/linux/releases/33/Cloud/x86_64/images/Fedora-Cloud-Base-33-1.2.x86_64.qcow2
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_ds_src: ./resources/cloud-init/ds_v2/DataSourceRbxCloud.py
cloud_init_install: true
custom_scripts:
  - ./scripts/resolv.sh
  - ./scripts/fstab.sh
  - ./scripts/fedora/fedora-31.sh
  - ./scripts/fedora/cli_dnf.sh
  - ./scripts/relabel.sh
  - ./scripts/check_df.sh
source_image: 'fedora:32'
uefi_support: false
selinux: '1'
format: qcow
