name: freebsd-13.0-server
distro: freebsd
edition: freebsd
codename: 'stable'
pname: FreeBSD 13.0
arch: x64
version: '13.0'
disk_size: '10'
cloud_init_install: true
template_file: templates/manual/freebsd-13.0.json
# uefi_support: true
