name: freebsd-12.1-server
distro: freebsd
edition: freebsd
codename: 'stable'
pname: FreeBSD 12.1
arch: x64
version: '12.1'
disk_size: '10'
cloud_init_install: true
template_file: templates/manual/freebsd-12.1.json
# uefi_support: true
# cli_support: true
repology_repo: 'freebsd'