name: freebsd-12.2-server
distro: freebsd
edition: freebsd
codename: 'stable'
pname: FreeBSD 12.2
arch: x64
version: '12.2'
disk_size: '10'
cloud_init_install: true
template_file: templates/manual/freebsd-12.2.json
# uefi_support: true
