name: freebsd-12.1-server
distro: freebsd
edition: freebsd
codename: 'stable'
pname: FreeBSD 12.1 Server
arch: x64
version: '12.1'
disk_size: '5'
cloud_init_install: true
template_file: templates/manual/freebsd-12.1.json
# uefi_support: '1'
