name: rhel-7
distro: rhel
edition: server
codename: 'stable'
pname: "Red Hat Enterprise Linux 7"
arch: x64
version: '7'
disk_size: '10'
cloud_init_install: true
vm_builder_service: 'rhel.build'
template_file: templates/manual/rhel-7.json
source_image: rhel:7
# uefi_support: true
# cli_support: true
scope:
  - h1
license: true