name: rhel-7 for SAP HANA
distro: rhel
edition: sap-hana
codename: 'stable'
pname: RHEL 7 for SAP HANA
arch: x64
version: '7'
disk_size: '10'
cloud_init_install: true
vm_builder_service: 'rhel.build'
template_file: templates/manual/rhel-7-sap-hana.json
source_image: rhel:7
# uefi_support: true
scope:
  - h1
license: true