name: rhel-7 for SAP
distro: rhel
edition: sap
codename: 'stable'
pname: "Red Hat Enterprise Linux 7 for SAP"
arch: x64
version: '7'
disk_size: '10'
cloud_init_install: true
vm_builder_service: 'rhel.build'
template_file: templates/manual/rhel-7-sap.json
source_image: rhel:7
# uefi_support: true
scope:
  - h1
license: true