name: rhel-8
distro: rhel
edition: server
codename: 'stable'
pname: RHEL 8
arch: x64
version: '8'
disk_size: '5'
cloud_init_install: true
vm_builder_service: 'rhel.build'
template_file: templates/manual/rhel-8.json
# uefi_support: '1'
scope:
  - h1
