name: ubuntu-1604-xenial
codename: xenial xerus
pname: Ubuntu 16.04 (xenial xerus)
distro: ubuntu
edition: server
arch: x64
version: '16.04'
download_url: >-
  http://cloud-images.ubuntu.com/releases/xenial/release/ubuntu-16.04-server-cloudimg-amd64-disk1.img
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_install: false
custom_scripts:
  - ./scripts/resolv.sh
  - ./scripts/fstab.sh
  - ./scripts/ubuntu/ubuntu-1604.sh
  - ./scripts/ubuntu/cli.sh
  - ./scripts/apt_clean.sh
  - ./scripts/check_df.sh
uefi_support: true
format: qcow
