name: ubuntu-1604-desktop-xenial
codename: xenial xerus
pname: Ubuntu 16.04 Desktop (xenial xerus)
distro: ubuntu
edition: desktop
arch: x64
version: '16.04'
download_url: >-
  http://cloud-images.ubuntu.com/releases/xenial/release/ubuntu-16.04-server-cloudimg-amd64-disk1.img
disk_size: '10'
qcow_part: /dev/sda1
cloud_init_install: false
vm_gen1_test_service:
  h1: a1.medium
  rbx: medium
custom_scripts:
  - ./scripts/resolv.sh
  - ./scripts/fstab.sh
  - ./scripts/ubuntu/ubuntu-1604.sh
  - ./scripts/ubuntu/ubuntu-1604-desktop.sh
  - ./scripts/ubuntu/cli.sh
  - ./scripts/check_df.sh
source_image: 'fedora:31'
uefi_support: true
format: qcow
