name: ubuntu-2410-oracular
codename: oracular oriole
pname: Ubuntu 24.10 (Oracular Oriole)
distro: ubuntu
edition: server
arch: x64
version: '24.10'
build: true
download_url: 'https://cloud-images.ubuntu.com/releases/oracular/release/ubuntu-24.10-server-cloudimg-amd64.img'
format: qcow
qcow_part: /dev/sda1
qcow_boot_part: /dev/sda13
disk_size: '5'
# cloud_init_ds_src: ./resources/cloud-init/ds_v3/DataSourceRbxCloud.py
cloud_init_install: false
custom_scripts:
  # - ./scripts/resolv.sh
  - ./scripts/disable-llmr-mdns.sh
  - ./scripts/fstab.sh
  - ./scripts/ubuntu/ubuntu-2410.sh
  # - ./scripts/ubuntu/cli.sh
  - ./scripts/apt_clean.sh
  - ./scripts/check_df.sh
  - ./scripts/io_scheduler.sh
  - ./scripts/patch-cloud-init.sh
uefi_support: true

source:
  url: 'https://cloud-images.ubuntu.com/releases/oracular/release/ubuntu-24.10-server-cloudimg-amd64.img'
  type: qcow
  mount:
    root: p1
    boot: p13