name: ubuntu-2010-groovy
codename: groovy gorilla
pname: Ubuntu 20.10 (groovy gorilla)
distro: ubuntu
edition: server
arch: x64
version: '20.10'
download_url: 'https://cloud-images.ubuntu.com/releases/groovy/release/ubuntu-20.10-server-cloudimg-amd64.img'
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_install: false
custom_scripts:
  - ./scripts/resolv.sh
  - ./scripts/fstab.sh
  - ./scripts/ubuntu/ubuntu-1710.sh
  # - ./scripts/ubuntu/cli.sh
  - ./scripts/apt_clean.sh
  - ./scripts/check_df.sh
uefi_support: true
format: qcow
