name: ubuntu-2004-focal
codename: focal fossa
pname: Ubuntu 20.04 (focal fossa)
distro: ubuntu
edition: server
arch: x64
version: '20.04'
download_url: 'https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img'
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_ds_src: ./resources/cloud-init/ds_v2/DataSourceRbxCloud.py
cloud_init_install: true
custom_scripts:
  - ./scripts/fstab.sh
  - ./scripts/ubuntu/ubuntu-1710.sh
  - ./scripts/ubuntu/cli.sh
uefi_support: '1'
format: qcow
