name: ubuntu-2004-focal
codename: focal fossa
pname: Ubuntu 20.04 Desktop (focal fossa)
distro: ubuntu
edition: desktop
arch: x64
version: '20.04'
download_url: 'https://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64.img'
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_install: false
vm_gen1_test_service:
  h1: a1.medium
  rbx: medium
custom_scripts:
  - ./scripts/fstab.sh
  - ./scripts/ubuntu/ubuntu-1710.sh
  - ./scripts/ubuntu/ubuntu-1904-desktop.sh
  - ./scripts/ubuntu/cli.sh
uefi_support: true
format: qcow
