name: ubuntu-1910-eoan
codename: eoan ermine
pname: Ubuntu 19.10 (eoan ermine)
distro: ubuntu
edition: server
arch: x64
version: '19.10'
download_url: 'https://cloud-images.ubuntu.com/releases/eoan/release/ubuntu-19.10-server-cloudimg-amd64.img'
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_ds_src: ./resources/cloud-init/ds_v2/DataSourceRbxCloud.py
cloud_init_ds_dir: /usr/lib/python3/dist-packages/cloudinit/sources/
custom_scripts:
  - ./scripts/fstab.sh
  - ./scripts/ubuntu/ubuntu-1710.sh
  - ./scripts/ubuntu/cli.sh
# uefi_support: '1'
format: qcow
