name: ubuntu-1804-bionic
codename: bionic beaver
pname: Ubuntu 18.04 Desktop (bionic beaver)
distro: ubuntu
edition: desktop
arch: x64
version: '18.04'
download_url: >-
  http://cloud-images.ubuntu.com/daily/server/bionic/current/bionic-server-cloudimg-amd64.img
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_ds_src: ./resources/cloud-init/ds_v2/DataSourceRbxCloud.py
cloud_init_ds_dir: /usr/lib/python3/dist-packages/cloudinit/sources/
custom_scripts:
  - ./scripts/fstab.sh
  - ./scripts/ubuntu/ubuntu-1710.sh
  - ./scripts/ubuntu/ubuntu-1804-desktop.sh
  - ./scripts/ubuntu/cli.sh
uefi_support: '1'
format: qcow
