name: ubuntu-2104-hirsute
codename: hirsute hippo
pname: Ubuntu 21.04 (hirsute hippo)
distro: ubuntu
edition: server
arch: x64
version: '21.04'
download_url: 'https://cloud-images.ubuntu.com/releases/hirsute/release/ubuntu-21.04-server-cloudimg-amd64.img'
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_install: false
custom_scripts:
  - ./scripts/resolv.sh
  - ./scripts/fstab.sh
  - ./scripts/ubuntu/ubuntu-1710.sh
  # - ./scripts/ubuntu/cli.sh
  - ./scripts/apt_clean.sh
  - ./scripts/check_df.sh
uefi_support: true
format: qcow
