name: ubuntu-1804-bionic
codename: bionic beaver
pname: Ubuntu 18.04 (bionic beaver)
distro: ubuntu
edition: server
arch: x64
version: '18.04'
download_url: >-
  http://cloud-images.ubuntu.com/releases/bionic/release/ubuntu-18.04-server-cloudimg-amd64.img
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_install: false
custom_scripts:
  - ./scripts/resolv.sh
  - ./scripts/fstab.sh
  - ./scripts/ubuntu/ubuntu-1710.sh
  - ./scripts/ubuntu/cli.sh
  - ./scripts/check_df.sh
uefi_support: true
format: qcow
