name: ubuntu-1810-cosmic
codename: cosmic cuttlefish
pname: Ubuntu 18.10 (cosmic cuttlefish)
distro: ubuntu
edition: server
arch: x64
version: '18.10'
download_url: >-
  http://cloud-images.ubuntu.com/releases/cosmic/release/ubuntu-18.10-server-cloudimg-amd64.img
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_ds_src: ./resources/cloud-init/ds_v2/DataSourceRbxCloud.py
cloud_init_ds_dir: /usr/lib/python3/dist-packages/cloudinit/sources/
custom_scripts:
  - ./scripts/ubuntu/ubuntu-1710.sh
  - ./scripts/ubuntu/cli.sh
uefi_support: '1'
format: qcow
