name: ubuntu-1904-disco
codename: disco dingo
pname: Ubuntu 19.04 (disco dingo)
distro: ubuntu
edition: server
arch: x64
version: '19.04'
download_url: 'http://cloud-images.ubuntu.com/releases/disco/release/ubuntu-19.04-server-cloudimg-amd64.img'
disk_size: '5'
qcow_part: /dev/sda1
cloud_init_ds_src: ./resources/cloud-init/ds_v2/DataSourceRbxCloud.py
cloud_init_ds_dir: /usr/lib/python3/dist-packages/cloudinit/sources/
custom_scripts:
  - ./scripts/fstab.sh
  - ./scripts/ubuntu/ubuntu-1710.sh
  - ./scripts/ubuntu/cli.sh
# uefi_support: '1'
format: qcow
