name: windows-server-2016-standard-core
codename: ""
pname: MS Windows Server 2016 Standard Core
distro: windows
release: "2016"
edition: standard-core
arch: x64
version: "2016"
# not public available due licensing issue
iso: autounattend-ws2016-std-core-bios.xml.iso-r4
disk_size: "25"
disk_type: ssd
vm_type: m2.large
image_recommended_disk_size: "50"
image_recommended_vm_type: m2.large
#base_image: base-windows-server-2016-standard
# not public available due licensing issue
base_image: 5a3cdc85d919342e40231bf6
test_set: 'windows'
mode: 'windows'
scope:
  - h1
license: true
priority: 100