name: windows-server-2016-standard-core
codename: ""
pname: MS Windows Server 2016 Standard Core
distro: windows
release: "2016"
edition: standard-core
arch: x64
version: "2016"
iso: 598afd7fcd7f442cad2c89cc
disk_size: "25"
disk_type: ssd
vm_type: m2.medium
image_recommended_disk_size: "50"
image_recommended_vm_type: m2.large
#base_image: base-windows-server-2016-standard
# not public available due licensing issue
base_image: 5a3cdc85d919342e40231bf6
test_set: 'windows'
mode: 'windows'
