name: fedora-29
codename: core
pname: Fedora 29
distro: fedora
edition: server
arch: x64
version: '28'
download_url: >-
  https://download.fedoraproject.org/pub/fedora/linux/releases/29/Cloud/x86_64/images/Fedora-Cloud-Base-29-1.2.x86_64.qcow2
disk_size: '2'
qcow_part: /dev/sda1
cloud_init_ds_src: ./resources/cloud-init/ds_v2/DataSourceRbxCloud.py
cloud_init_ds_dir: /usr/lib/python3.7/site-packages/cloudinit/sources
custom_scripts:
  - ./scripts/fedora/fedora-28.sh
  - ./scripts/fedora/fedora-29.sh
uefi_support: '0'
selinux: '1'