name: ubuntu-1710-artful
codename: artful aardvark
pname: Ubuntu 17.10 (artful aardvark)
distro: ubuntu
edition: server
arch: x64
version: '17.10'
download_url: >-
  http://cloud-images-archive.ubuntu.com/releases/artful/release-20180706/ubuntu-17.10-server-cloudimg-amd64.img
disk_size: '2'
qcow_part: /dev/sda1
cloud_init_ds_dir: /usr/lib/python3/dist-packages/cloudinit/sources/
custom_scripts:
  - ./scripts/ubuntu/ubuntu-1710.sh
uefi_support: '1'
