name: ubuntu-1804-bionic
codename: bionic beaver
pname: Ubuntu 18.04 (bionic beaver)
distro: ubuntu
edition: server
arch: x64
version: '18.04'
download_url: >-
  http://cloud-images.ubuntu.com/releases/bionic/release/ubuntu-18.04-server-cloudimg-amd64.img
disk_size: '2'
qcow_part: /dev/sda1
cloud_init_ds_src: ./resources/cloud-init/ds_v2/DataSourceRbxCloud.py
cloud_init_ds_dir: /usr/lib/python3/dist-packages/cloudinit/sources/
custom_scripts:
  - ./scripts/ubuntu/ubuntu-1710.sh
uefi_support: '1'
