name: Build

on:
  push:
    branches-ignore:
      - 'master'
  schedule:
    - cron:  '0 0 * * *'
jobs:
  config:
    runs-on: self-hosted
    outputs:
      matrix-packer: ${{ steps.set-matrix.outputs.matrix-packer }}
      matrix-windows: ${{ steps.set-matrix.outputs.matrix-windows }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install
        run: npm ci
      - name: Fetch master branch
        run: git fetch origin master:master
      - id: set-matrix
        name: Identify diff
        run: node ./.github/render_matrix.js --github --diff
  packer:
    needs: config
    runs-on: self-hosted
    timeout-minutes: 90
    env:
      SCOPE: '${{matrix.scope}}'
      CONFIG: '${{matrix.config}}'
      H1_TOKEN: '${{secrets.H1_TOKEN}}'
      RBX_TOKEN: '${{secrets.RBX_TOKEN}}'
      INFLUXDB_HOST: '${{secrets.INFLUXDB_HOST}}'
      INFLUXDB_PASSWORD: '${{secrets.INFLUXDB_PASSWORD}}' 
      INFLUXDB_USER: '${{secrets.INFLUXDB_USER}}'
      REDHAT_SECRET: '${{secrets.REDHAT_SECRET}}'
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix: ${{fromJson(needs.config.outputs.matrix-packer)}}
    steps:
      - uses: actions/checkout@v2
      - name: apply workaround for IP conflict bug
        run: sleep $(shuf -i 60-120 -n 1)
      - name: Save private SSH key
        run: |
          echo "$PRIVATE_KEY" | openssl base64 -d > ./resources/secrets/id_rsa;
          rm ./resources/ssh/id_rsa*;
          cp ./resources/secrets/* ./resources/ssh/;
          md5sum ./resources/ssh/*
        env:
          PRIVATE_KEY: "${{ secrets.PRIVATE_KEY }}" 
      - name: Build Docker image
        run: docker build -t recommended-images:${{github.sha}} .
      - name: Build Platform image
        run: |
          publish_arg="" && [[ "$GITHUB_EVENT_NAME" =~ "schedule" ]]  && publish_arg="--publish" ;
          docker run --rm -e H1_TOKEN -e RBX_TOKEN -e SCOPE -e INFLUXDB_HOST -e INFLUXDB_PASSWORD -e INFLUXDB_USER -e REDHAT_SECRET \
          recommended-images:${{github.sha}} \
          nodejs buildTestPublish.js --config "$CONFIG" --mode "packer" --cleanup ${publish_arg}
      - name: Retry build Platform image
        run: |
          publish_arg="" && [[ "$GITHUB_EVENT_NAME" =~ "schedule" ]]  && publish_arg="--publish" ;
          docker run --rm -e H1_TOKEN -e RBX_TOKEN -e SCOPE -e INFLUXDB_HOST -e INFLUXDB_PASSWORD -e INFLUXDB_USER -e REDHAT_SECRET \
          recommended-images:${{github.sha}} \
          nodejs buildTestPublish.js --config "$CONFIG" --mode "packer" --cleanup ${publish_arg}
        if: ${{ steps.first.outcome == 'failure' }}
      - name: "Report successfully build to InfluxDB"
        run: ./.github/influx.sh
        if: "${{ success() }}"
        env:
          INFLUXDB_VALUE: "1"
      - name: "Report failure build to InfluxDB"
        run: ./.github/influx.sh
        if: "${{ failure() }}"
        env:
          INFLUXDB_VALUE: "0"  
  windows:
    needs: config
    timeout-minutes: 720
    runs-on: self-hosted
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix: ${{fromJson(needs.config.outputs.matrix-windows)}}
    env:
      SCOPE: '${{matrix.scope}}'
      CONFIG: '${{matrix.config}}'
      H1_TOKEN: '${{secrets.H1_TOKEN}}'
      RBX_TOKEN: '${{secrets.RBX_TOKEN}}'
      INFLUXDB_HOST: '${{secrets.INFLUXDB_HOST}}'
      INFLUXDB_PASSWORD: '${{secrets.INFLUXDB_PASSWORD}}' 
      INFLUXDB_USER: '${{secrets.INFLUXDB_USER}}'
      REDHAT_SECRET: '${{secrets.REDHAT_SECRET}}'
    steps:
      - uses: actions/checkout@v2
      - name: apply workaround for IP conflict bug
        run: sleep $(shuf -i 60-120 -n 1)
      - name: Save private SSH key
        run: echo $PRIVATE_KEY > ./resources/secrets/id_rsa
        env:
          PRIVATE_KEY: "${{ secrets.PRIVATE_KEY }}" 
      - name: Build Docker image
        run: docker build -f Dockerfile.windows  -t recommended-images-windows:${{github.sha}} .
      - name: Build Platform image
        run: |
          publish_arg="" && [[ "$GITHUB_EVENT_NAME" =~ "schedule" ]]  && publish_arg="--publish" ;
          docker run --rm -e H1_TOKEN -e SCOPE \
          recommended-images-windows:${{github.sha}} \
          nodejs buildTestPublish.js --config "$CONFIG" --mode "windows" --cleanup ${publish_arg}